package user;


import java.rmi.RemoteException;

import javax.ejb.EJBObject;


import java.util.*;
import bean.*;
import facture.*;
import finance.*;
import historique.*;
import penalite.*;
import facturefournisseur.*;
import pcg.*;
import pointage.*;
import lc.*;
import ded.*;
import facturefournisseur.*;
import java.sql.Connection;
import javax.ejb.Remote;
import stock.*;
import pub.*;

@Remote
public interface UserEJBRemote     extends EJBObject{
   public ResultatEtSomme getDataPageGroupe(ClassMAPTable e, String[] groupe, String[] sommeGroupe,String[]moyenneGroupe, String[] colInt, String[] valInt, int numPage, String apresWhere, String[] nomColSomme, String ordre, Connection c, int npp) throws Exception ;
  public TypeObjet[] findTypeObjet(String nomTable, String id, String typ) throws Exception, RemoteException;
  public String createTypeObjet(String nomTable, String proc, String pref, String typ, String desc) throws Exception, RemoteException;
  public String updateTypeObjet(String table, String id, String typ, String desc) throws Exception, RemoteException;
  public int deleteTypeObjet(String nomTable, String id) throws Exception, RemoteException;
  public String createFactureMere(String daty, String periodeDebut, String periodeFin, String idClient, String noteExplicative, String idTva, String idFactureEn, String idDeviseEn, String reduction, String idSCatService, String idTypePaim, String respe, String entite, String parution) throws Exception, RemoteException;
  public int deleteFactureMere(String idFactureMere) throws Exception, RemoteException;
  public String updateFactureMere(String idFactureMere, String daty, String idClient, String periodeDebut, String periodeFin, String noteExplicative, String idTva, String idDeviseEn, String reduction, String idFactureEn, String idCoursChange, String dateLimite, String idEtat, String montantAPayer, String idSCatService) throws Exception, RemoteException;
  public ResultatEtSomme findClientPage(String idClient, String nomClient, String idregime, String tel, String fax, String adr, String numStat, String nif, String rc, String tp, String quit, int numPage) throws Exception, RemoteException;
  public FactMere[] findFactureMere(String datyinf, String datySup, String idFactureMere, String client, String dateLimite, String etatFacture, String catService, String sCatService) throws Exception, RemoteException;
  public FactMere[] findFactureMereDevise(String datyinf, String datySup, String idFactureMere, String client, String dateLimite, String etatFacture, String catService, String sCatService, String devise) throws Exception, RemoteException;
  public FactMere[] findFactureMereDeviseResp(String datyinf, String datySup, String idFactureMere, String client, String dateLimite, String etatFacture, String catService, String sCatService, String devise, String resp) throws Exception, RemoteException;
  public FactMere[] findFactureMereDeviseRespEntite(String datyinf, String datySup, String idFactureMere, String client, String dateLimite, String etatFacture, String catService, String sCatService, String devise, String resp, String entite) throws Exception, RemoteException;
    public String createClientComptable(String nomClient, String idregime, String tel, String fax, String adr, String numStat, String nif, String rc, String tp, String quit, String idComptable, String typecontact, String soustypecontact) throws Exception;
  public String createClient(String nomClient, String idregime, String tel, String fax, String adr, String numStat, String nif, String rc, String tp, String quit) throws Exception, RemoteException;
  public String updateClient(String idClient, String nomClient, String idregime, String tel, String fax, String adr, String numStat, String nif, String rc, String tp, String quit) throws Exception, RemoteException;
  public int deleteClient(String idClient) throws Exception, RemoteException;
  public Client[] findClient(String idClient, String nomClient, String idregime, String tel, String fax, String adr, String numStat, String nif, String rc, String tp, String quit) throws Exception, RemoteException;
  public String createFactureFille(String idFactureMere, String refObj, String des, String qte, String unite, String pu, String reductionF) throws Exception, RemoteException;
  public int deleteFactureFille(String idFactureFille) throws Exception, RemoteException;
  public String updateFactureFille(String idFactureFille, String idFactureMere, String refObj, String des, String qte, String unite, String pu, String reductionF) throws Exception, RemoteException;
  public FactureFille[] findFactureFille(String idFactureFille, String refObj, String idSCatService, String idFactureMere) throws Exception, RemoteException;
  public String createFactureRedevance(String idClient, String daty, String dateDebut, String datyFin, String sCatService) throws Exception, RemoteException;
  public float calculPenalite(String datyDebut, String datyFin, String idSCatService) throws ErreurDAO, RemoteException;
  public String createAutorisationAnnulation(String idObjet, String responsable, String daty, String motif, String idTypeObjet) throws Exception, RemoteException;
  public int deleteAutorisationAnnulation(String idAutorisation) throws Exception, RemoteException;
  public String updateAutorisationAnnulation(String idAutorisation, String idObjet, String responsable, String daty, String motif, String idTypeObjet) throws Exception, RemoteException;
  public AutorisationAnnulation[] findAutorisationAnnulation(String idAutorisation, String idObjet, String responsable, String daty1, String daty2, String motif, String idTypeObjet) throws Exception, RemoteException;
  public String createService(String sCatService, String datyDebutValid, String unite, String des, String pu, String devise, String tva, String idClient) throws Exception, RemoteException;
  public int deleteService(String idService) throws Exception, RemoteException;
  public String updateService(String idService, String sCatService, String datyDebutValid, String unite, String des, String pu, String devise, String tva, String idClient) throws Exception, RemoteException;
  public Service[] findService(String idService, String idSCatService, String daty1, String daty2, String unite, String des, String devise, String idClient) throws Exception, RemoteException;
  public String createSCatService(String nomSCat, String cat, String periodeFacturation, String factureEn) throws Exception, RemoteException;
  public int deleteSCatService(String idSCatService) throws Exception, RemoteException;
  public String updateSCatService(String idSCatService, String nomSCat, String cat, String periodeFacturation, String factureEn) throws Exception, RemoteException;
  public String createCaisseComptable(String descCaisse, String respCaisse, String comptable) throws Exception, RemoteException;
  public String createCaisse(String descCaisse, String respCaisse) throws Exception, RemoteException;
  public String updateCaisse(String idCaisse, String descCaisse, String respCaisse, String etatCaisse) throws Exception, RemoteException;
  public int deleteCaisse(String idCaisse) throws Exception, RemoteException;
  public Caisse[] findCaisse(String idCaisse, String descCaisse, String respCaisse, String etatCaisse) throws Exception, RemoteException;
  public String createSortie(String datee, String desi, String mont, String ben, String typ, String dev, String mode, String cais, String rem, String parution, String agence, String prj, String part, String fact, String idLigne) throws Exception, RemoteException;
  public String updateSortie(String idSortie, String datee, String desi, String mont, String ben, String typ, String dev, String mode, String cais, String eta, String rem, String prj, String part, String fact) throws Exception, RemoteException;
  public int deleteSortie(String idSortie) throws Exception, RemoteException;
  public Sortie[] findSortie(String idSortie, String daty1, String daty2, String beneficiaire, String typeSortie, String designation, String idModePaiement, String idDevise, String idCaisse, String idEtat) throws Exception, RemoteException;
  public Sortie[] findSortieSourceCaisse(String idSortie, String daty1, String daty2, String beneficiaire, String typeSortie, String designation, String idModePaiement, String idDevise, String idCaisse, String idEtat, String sourceC) throws Exception, RemoteException;
  public Sortie[] findSortieAgence(String idSortie, String daty1, String daty2, String beneficiaire, String typeSortie, String designation, String idModePaiement, String idDevise, String idCaisse, String idEtat, String parution, String agence, String colonne, String ordre, String prj, String part, String fact, String idLigne) throws Exception, RemoteException;
  public Sortie[] findSortieLettre(String idSortie, String daty1, String daty2, String beneficiaire, String typeSortie, String designation, String idModePaiement, String idDevise, String idCaisse, String idEtat, String parution, String agence, String colonne, String ordre, String prj, String part, String fact, String aW) throws Exception, RemoteException;
  public String createEntree(String datee, String desi, String mont, String sour, String typ, String n_pie, String dev, String mode, String cais, String rem, String paru, String agence, String source, String prj, String part, String idLigne) throws Exception, RemoteException;
  public String updateEntree(String idEntree, String datee, String desi, String mont, String sour, String typ, String n_pie, String dev, String mode, String cais, String eta, String rem, String prj, String part, String idLigne) throws Exception, RemoteException;
  public int deleteEntree(String idEntree) throws Exception, RemoteException;
  public Entree[] findEntreePiece(String idEntree, String daty1, String daty2, String client, String typeEntree, String designation, String idModePaiement, String numPiece, String idDevise, String idCaisse, String idEtat) throws Exception, RemoteException;
  public Entree[] findEntreeAgence(String idEntree, String daty1, String daty2, String client, String typeEntree, String designation, String idModePaiement, String numPiece, String idDevise, String idCaisse, String idEtat, String agence, String parution, String colonne, String ordre) throws Exception, RemoteException;
  public Entree[] findEntreeLettre(String idEntree, String daty1, String daty2, String client, String typeEntree, String designation, String idModePaiement, String numPiece, String idDevise, String idCaisse, String idEtat, String agence, String parution, String colonne, String ordre, String prj, String part, String apresWhere) throws Exception, RemoteException;
  public Entree[] findEntreeLettrePage(String idEntree, String daty1, String daty2, String client, String typeEntree, String designation, String idModePaiement, String numPiece, String idDevise, String idCaisse, String idEtat, String agence, String parution, String colonne, String ordre, String prj, String part, String apresWhere, int numPa) throws Exception, RemoteException;
  public Entree[] findEntree(String idEntree, String daty1, String daty2, String client, String typeEntree, String designation, String idModePaiement, String idDevise, String idCaisse, String idEtat) throws Exception, RemoteException;
  public Entree[] findEntreeBenCaisse(String idEntree, String daty1, String daty2, String client, String typeEntree, String designation, String idModePaiement, String idDevise, String idCaisse, String idEtat, String benCaisse) throws Exception, RemoteException;
  public String createHistorique(String dateHistorique, String heure, String objet, String action, String refuser, String refObjet) throws Exception, RemoteException;
  public String updateHistorique(String idHistorique, String dateHistorique, String heure, String objet, String action, String refuser, String refObjet) throws Exception, RemoteException;
  public int deleteHistorique(String idHistorique) throws Exception, RemoteException;
  public MapHistorique[] findHistoriquePage(String refuser, String refObjet, String objet, String action, String daty1, String daty2, int numPage) throws Exception, RemoteException;
  public MapHistorique[] findHistorique(String refuser, String refObjet, String objet, String action, String daty1, String daty2) throws Exception, RemoteException;
  public String createHistoriqueEtat(String idMere, String idUser, String idEtat, String dateModification) throws Exception, RemoteException;
  public String updateHistoriqueEtat(String idHistoriqueEtat, String idMere, String idUser, String idEtat, String dateModification) throws Exception, RemoteException;
  public int deleteHistoriqueEtat(String idHistoriqueEtat) throws Exception, RemoteException;
  public HistoriqueEtat[] findHistoriqueEtat(String idHistoriqueEtat, String idMere, String idUser, String idEtat, String dateModification) throws Exception, RemoteException;
  public String createAccident(String datySaisie, String datyAccident, String description, String nomEmploye, String rem) throws ErreurDAO, RemoteException;
  public String updateAccident(String idAccident, String datySaisie, String datyAccident, String description, String nomEmploye, String rem) throws ErreurDAO, RemoteException;
  public int deleteAccident(String idAccident) throws Exception, RemoteException;
  public Accident[] findAccident(String idAccident, String datySaisie, String datyAccident, String description, String nomEmploye) throws Exception, RemoteException;
  public String createChiffreAffTac(String mois, String annee, String montant) throws ErreurDAO, RemoteException;
  public String updateChiffreAffTac(String idChiffre, String mois, String annee, String montant) throws ErreurDAO, RemoteException;
  public int deleteChiffreAffTac(String idChiffre) throws Exception, RemoteException;
  public ChiffreAffTac[] findChiffreAffTac(String idChiffre, String mois, String annee, String montant) throws Exception, RemoteException;
  public int annulerChiffreAffTac(String idChiffre) throws Exception, RemoteException;
  public String createVolCont(String datySaisie, String datyVol, String numCont, String designation, String idDossier, String proprietaire, String montant) throws ErreurDAO, RemoteException;
  public String updateVolCont(String idVol, String datySaisie, String datyVol, String numCont, String designation, String idDossier, String proprietaire, String montant) throws ErreurDAO, RemoteException;
  public int deleteVolCont(String idVol) throws Exception, RemoteException;
  public VolConteneur[] findVolCont(String idVol, String datyInf, String datySup, String numCont, String designation, String idDossier, String proprietaire, String montant) throws Exception, RemoteException;
  public String createDommageConteneur(String datyDebut, String datyFin, String designation, String montant, String idDossier, String nomProprietaire) throws ErreurDAO, RemoteException;
  public String updateDommageConteneur(String idDommage, String datySaisie, String datyDommage, String designation, String montant, String idDossier, String nomProprietaire) throws ErreurDAO, RemoteException;
  public int deleteDommageConteneur(String idDommage) throws Exception, RemoteException;
  public DommageConteneur[] findDommageConteneur(String idDommage, String datyInf, String datySup, String designation, String montant, String idDossier, String nomProprietaire) throws Exception, RemoteException;
  public String updateParametrePenalite(String tauxDirBcEurop, String majorBcEurop, String delaiPaiementPenalit, String performAnnuel, String slTauxOccup, String majorTauxOccup, String slRappPerteAnnu, String slNbPerteAnnu, String pxUnitVol, String slRappDommagTotal, String pxPourcExc, String valLimitcont, String nbLimitAccAnnu, String datyD, String pxAccExc) throws Exception, RemoteException;
  public ParametrePenalite[] findParametrePenalite(String idParametrePenalite, String tauxDirBcEurop, String majorBcEurop, String delaiPaiementPenalit, String performAnnuel, String slTauxOccup, String majorTauxOccup, String slRappPerteAnnu, String slNbPerteAnnu, String pxUnitVol, String slRappDommagTotal, String pxPourcExc, String valLimitcont, String nbLimitAccAnnu, String pxAccExc, String date1) throws ErreurDAO, RemoteException;
  public String createTva(String val, String daty) throws Exception, RemoteException;
  public String updateTva(String idTva, String val, String daty) throws Exception, RemoteException;
  public int deleteTva(String idTva) throws Exception, RemoteException;
  public Tva[] findTva(String idTva, String val, String daty1, String daty2) throws Exception, RemoteException;
  public String createUtilisateurs(String loginuser, String pwduser, String nomuser, String adruser, String teluser, String idrole) throws Exception, RemoteException;
  public String updateUtilisateurs(String refuser, String loginuser, String pwduser, String nomuser, String adruser, String teluser, String idrole) throws Exception, RemoteException;
  public int deleteUtilisateurs(String refuser) throws Exception, RemoteException;
  public MapUtilisateur[] findUtilisateurs(String refuser, String loginuser, String pwduser, String nomuser, String adruser, String teluser, String idrole) throws Exception, RemoteException;
  public String createFacturePenalite(String[] idPenalite) throws Exception, RemoteException;
  public String createPenalite(String dateDebut, String dateFin, String designation, String montant, String idSCatService, String champ1, String champ2, String champ3, String champ4) throws ErreurDAO, RemoteException;
  public String updatePenalite(String idPenalite, String dateDebut, String dateFin, String designation, String montant, String idSCatService, String champ1, String champ2, String champ3, String champ4) throws ErreurDAO, RemoteException;
  public int deletePenalite(String idPenalite) throws Exception, RemoteException;
  public Penalite[] findPenalite(String idPenalite, String daty, String designation, String montant, String idSCatService, String champ1, String champ2, String champ3, String champ4) throws Exception, RemoteException;
  public int annulerPenalite(String idPenalite) throws Exception, RemoteException;
  public int annulationFacture(String idFactureMere) throws Exception, RemoteException;
  public int verifChevauch(String datyFin, String idSCatService) throws Exception, RemoteException;
  public String updateParametreFacture(String dateLimite, String bonusEvp, String red, String dateDebutValid) throws Exception, RemoteException;
  public ParametreFacture[] findParametreFacture(String idParametreFacture, String dateLimite, String bonusEvp, String red, String date1, String date2) throws Exception, RemoteException;
  public SCatService[] findSCatService(String idSCatService, String nomSCat, String cat, String periodeFacturation) throws Exception, RemoteException;
  public facture.Societe findMaSociete(String idMaSociete, String nomMaSociete, String numCompte, String tel, String adr, String numStat, String nif, String rc, String tp, String quit) throws ErreurDAO, RemoteException;
  public facture.Societe[] findMaSocieteTab(String idMaSociete, String nomMaSociete, String numCompte, String tel, String adr, String numStat, String nif, String rc, String tp, String quit, String entite) throws ErreurDAO, RemoteException;
  public String updateMaSociete(String d, String no, String reg, String adr, String phone, String fa, String mai, String ger, String ni, String sta, String r, String cap, String b1, String b2, String log, String t, String q, String entite, String daty) throws Exception, RemoteException;
  public String createMaSociete(String d, String no, String reg, String adr, String phone, String fa, String mai, String ger, String ni, String sta, String r, String cap, String b1, String b2, String log, String t, String q, String entite, String daty) throws Exception, RemoteException;
  public MapRoles[] findRole(String descRole) throws Exception, RemoteException;
  public String createTrafic(String daty, String datyDebut, String datyFin, String nb, String rem, String idserv) throws ErreurDAO, RemoteException;
  public String updateTrafic(String idTrafic, String daty, String datyDebut, String datyFin, String nb, String rem, String idserv) throws ErreurDAO, RemoteException;
  public int deleteTrafic(String idTrafic) throws Exception, RemoteException;
  public TraficConteneur[] findTrafic(String idTrafic, String datyDebut, String datyFin, String idserv) throws Exception, RemoteException;
  public TraficConteneur[] findTraficPeriode(String idTrafic, String datyDebut, String datyFin, String idserv, String mois1, String mois2, String annee1, String annee2) throws Exception, RemoteException;
  public int annulerTrafic(String idTrafic) throws Exception, RemoteException;
  public ParametreFacture findParametreFactureEnCours(String daty) throws Exception, RemoteException;
  public MapUtilisateur getUser() throws RemoteException;
  //public double getSoldeMois(Date d)throws Exception, RemoteException;;
  public String finaliseFacture(String id) throws Exception, RemoteException;
  public ParametreFacture loadParametreFacture(String daty1) throws Exception, RemoteException;
  public ParametrePenalite loadParametrePenalite(String daty1) throws Exception, RemoteException;
  public int annulerEntree(String idEntree) throws Exception, RemoteException;
  public int annulerSortie(String idSortie) throws Exception, ErreurDAO, RemoteException;
  public int getMontantBilletage(String dix, String cinq, String deux, String un, String deuxCinq, String deuxCent, String cent, String cinquante, String vingt) throws RemoteException;
  public Change[] findChange(String idChange, String idDevise, String datyInf) throws Exception, RemoteException;
  public int verifPenalite(String mois, String annee) throws Exception, RemoteException;
  public Objet[] findObjet(String obj, String des) throws Exception, RemoteException;
  public Tva loadTva(String daty1) throws Exception, RemoteException;
  public String createFacturePenalite(String idPenalite) throws Exception, RemoteException;
  public Penalite[] findPenaliteNonFacture(String idPenalite, String daty, String designation, String montant, String idSCatService, String champ1, String champ2, String champ3, String champ4) throws Exception, RemoteException;
  public EtatFacture[] findEtatFacture(String idFact, String daty1, String daty2, String etat, String clien) throws Exception, RemoteException;
  public Change[] findChange(String idChange, String etat) throws Exception, RemoteException;
  public int desactiveUtilisateur(String ref) throws Exception, RemoteException;
  public int activeUtilisateur(String ref) throws Exception, RemoteException;
  public int testException() throws Exception, RemoteException;
  public EtatFacture[] findEtatFactureTaxe(String idFact, String daty1, String daty2, String etat, String clien, String scat, String devise) throws Exception, RemoteException;
  public Ecriture[] findEcriture(String idEcriture, String daty1, String daty2, String libelle, String compte, String piece) throws Exception, RemoteException;
  public Compte[] findCompte(String id, String typ, String desc, String daty) throws Exception, RemoteException;
  public String createAvoir(String idFact, String resp, String da, String mot, String mont, String typ) throws Exception, RemoteException;
  public String updateAvoir(String idAv, String idFact, String resp, String da, String mot, String mont) throws Exception, RemoteException;
  public Avoir[] findAvoir(String idAv, String idFact, String resp, String datyDebut, String datyFin, String mot, String typ) throws Exception, RemoteException;
  public Avoir[] findAvoirValide(String idAv, String idFact, String resp, String datyDebut, String datyFin, String mot, String typ) throws Exception, RemoteException;
  public int annulationAvoir(String idAvoir) throws Exception, RemoteException;
  public String createChange(String idDevise, String valeurEnAriary, String datyDebutValid) throws Exception, RemoteException;
  public String updateChange(String idChange, String idDevise, String valeurEnAriary, String s) throws RemoteException;
  public SynthesePointage[] finSynthese(String datyinf, String datySup) throws Exception, RemoteException;
  public int calculNombrePage(int nombreElement) throws RemoteException;
  public int calculHistoriquePage(String refuser, String refObjet, String objet, String action, String daty1, String daty2) throws Exception, RemoteException;
  public double calculChange(String valeur, String devise1, String devise2, String daty) throws Exception, RemoteException;
  public Change loadChangeValide(String devise, String datyInf) throws Exception, RemoteException;
  public String createBeneficiaireCompta(String va, String des, String comptable) throws Exception, RemoteException;
  public int annulerDevise(String idDevise) throws Exception, RemoteException;
  public int annulerCompte(String idCompte) throws Exception, RemoteException;
  public String createCompte(String val, String desc, String datyDebutVal) throws Exception, RemoteException;
  public double calculCA(String datyInf, String datySup) throws Exception, RemoteException;
  public String finaliseFactureUpdate(String idFact, String daty, String periodeDebut, String periodeFin, String idClient, String noteExplicative, String idTva, String idFactureEn, String idDeviseEn, String reduction, String idSCatService, String idTypePaim) throws Exception, RemoteException;
  public String createDetPenRetard(String idPenalit, String datyIn, String datySu, String rest, String nbJourRetar, String numPiec, String montat) throws Exception, RemoteException;
  public String updateDetPenRetard(String id, String idPenalit, String datyIn, String datySu, String rest, String nbJourRetar, String numPiec, String montat) throws Exception, RemoteException;
  public int deleteDetPenRetard(String id) throws Exception, RemoteException;
  public DetPenRetard[] findDetPenRetard(String id, String idPen, String daty1, String daty2, String nbJour, String numPiece) throws Exception, RemoteException;
  public SyntheseEVP[] findSyntheseEVP(String daty1, String daty2) throws Exception, RemoteException;
  public SyntheseEVP[] findSyntheseEVPMois(String mois, String annee) throws Exception, RemoteException;
  public int getNombreEVP(String mois, String annee) throws Exception, RemoteException;
  public int annulerAccident(String idAcc) throws Exception, RemoteException;
  public int annulerVol(String idVol) throws Exception, RemoteException;
  public int annulerDommage(String idDommage) throws Exception, RemoteException;
  public void testLogin(String user, String pass) throws Exception, RemoteException;
  public ResultatEtSomme findVirement(String nomtable, String dev, String caisse1, String caisse2, String mode, String daty1, String daty2, String apreW, int numPage) throws Exception, RemoteException;
  public SaisieVirement virer(String montant, String devise, String caisse1, String caisse2, String mode, String remarque, String daty) throws Exception, RemoteException;
  public Visa viserVirement(String idVir, String daty, String rem) throws Exception, RemoteException;
  public boolean virer(String daty, String caisse1, String caisse2, String montant, String remarque, String devise, String mode, String typeE, String typeS, String prj, String part, String fact, String idLigne) throws Exception, RemoteException;
  public EtatCaisseReste[] findEtatCaisseResteMvt(String daty1, String daty2, String caisse, String entite) throws Exception, RemoteException;
  public EtatCaisseReste[] findEtatCaisseReportMvt(String daty1, String daty2, String caisse, String entite) throws Exception, RemoteException;
  public ResultatEtSomme findReportPage(String daty1, String daty2, String caisse, String devise, int numP) throws Exception, RemoteException;
  public Report[] findReport(String daty1, String daty2, String caisse, String devise) throws Exception, RemoteException;
  public Report reporter(String daty, String montant, String caisse, String devise) throws Exception, RemoteException;
  public boolean reporter(String daty, String datyFin, String montant, String caisse, String devise, String prj, String part, String fact, String idLigne) throws Exception, RemoteException;
  public EtatFacture[] findEtatFactureResp(String idFact, String daty1, String daty2, String etat, String clien, String resp) throws Exception, RemoteException;
  public EtatFacture[] findEtatFactureRespTypeEntite(String idFact, String daty1, String daty2, String etat, String clien, String resp, String type, String entite, String parution) throws Exception, RemoteException;
  public String createEntryFacture(String numFact, String designation, String date, String frns, String tva, String mTTC, String rmq, String datee, String idDevise, String nature) throws Exception, RemoteException;
  public String createEntryFacture(String numFact, String designation, String date, String frns, String tva, String mTTC, String rmq, String datee, String idDevise) throws Exception, RemoteException;
  public ResultatEtSomme findFactureFournisseurPage(String nomTable, String num, String dateDebut, String dateFin, String fournisseur, String designation, String colonne, String ordre, String apresW, int numPage) throws Exception, RemoteException;
  public FactureFournisseur[] findFactureFournisseur(String num, String dateDebut, String dateFin, String fournisseur, String designation, String colonne, String ordre, String apresW) throws Exception, RemoteException;
  public FactureFournisseur[] findFactureF(String num, String dateDebut, String dateFin, String fournisseur, String projet, String etat, String colonne, String ordre, String apresW) throws Exception, RemoteException;
  public FactureFournisseur annulerFact(String nomTable, String nomTableLiaison, String id) throws Exception, RemoteException;
  public String createFournisseur(String fournisseur, String nif, String stat, String tel, String email, String adresse) throws Exception, RemoteException;
  public Fournisseur[] findFournisseurF(String idF, String fournisseur, String nif, String stat, String tel, String email, String adresse, String apresW) throws Exception, RemoteException;
  public FactureFournisseur[] lolo() throws RemoteException;
  public String cloturerFactureFournisseur(String idf, String numFact, String designation, String daty, String fournisseur, String montantHT, String tva, String montantTTC, String remarque, String etat, String projet, String dateemission, String idDevise) throws Exception, RemoteException;
  public FactureFournisseur[] findSortieFactureFournisseur() throws RemoteException;
  public String ajouterCompte(String c, String lib, String pc) throws Exception, RemoteException;
  public String majCompte(String idCompte, String cpt, String lib, String pcpt) throws Exception, RemoteException;
  public Pcg[] findCompteTab(String idc, String cpt, String lib, String pcpt) throws Exception, RemoteException;
  public String findCompteTxt(String idc, String cpt, String lib, String pcpt) throws Exception, RemoteException;
  public FactMere[] findFactureMereNonPaye(String datyinf, String datySup, String idFactureMere, String client, String dateLimite, String etatFacture, String catService, String sCatService) throws Exception, RemoteException;
  public String createPointage(String user, String daty, String heure, String type, String remarque, String ip, String agence, String machine) throws Exception, RemoteException;
  public Pointage[] findPointage(String idPointage, String user, String datyInf, String DateSup, String heureInf, String heureSup, String type, String rem, String ip, String agence, String machine) throws Exception, RemoteException;
  public EtatCaisse[] findEtatCaisseDepense(String daty1, String daty2, String caisse, String benC) throws Exception, RemoteException;
  public EtatCaisse[] findEtatCaisseEntree(String daty1, String daty2, String caisse, String benC) throws Exception, RemoteException;
  public EtatCaisseReste[] findEtatCaisseReste(String dateDebut, String dateFin, String caisse, String entite) throws Exception, RemoteException;
  public SyntheseCompte[] findSyntheseCompteSortie(String daty1, String daty2, String idCaiss, String benC, String compte, String descComp) throws Exception, RemoteException;
  public SyntheseCompte[] findSyntheseCompteEntree(String daty1, String daty2, String idCaiss, String benC, String compte, String descComp) throws Exception, RemoteException;
  public SyntheseCompte[] findSyntheseCompteSortieType(String daty1, String daty2, String idCaiss, String benC, String compte, String descComp, String idT, String v) throws Exception, RemoteException;
  public SyntheseCompte[] findSyntheseCompteEntreeType(String daty1, String daty2, String idCaiss, String benC, String compte, String descComp, String idT, String v) throws Exception, RemoteException;
  public String createLC(String designation, double creditInitial, String idTypeLigne, String numCompte, String idEntite, String iddirection, String mois, int annee, String rmq, String nomTable) throws Exception, RemoteException;
  public String updateLC(LigneCredit lc, String nomTable) throws Exception, RemoteException;
  public String updateLC(String id, String designation, double creditInitial, double cm, double montEng, double montVise, double montFact, String idTypeLigne, String numCompte, String idEntite, String iddirection, String mois, int annee, String rmq, String nomTable) throws Exception, RemoteException;
  public String copierLCRecette(String mois, String annee, String mois0, String annee0) throws Exception, RemoteException;
  public String createLCRecette(String designation, String creditInitial, String idTypeLigne, String numCompte, String idEntite, String iddirection, String mois, String annee, String rmq) throws Exception, RemoteException;
  public String createLcMultiple(String designation, String creditInitial, String idTypeLigne, String numCompte, String idEntite, String iddirection, String mois, String annee, String paruInf, String paruSup, String nomTable) throws Exception, RemoteException;
  public String createLCe(String designation, double creditInitial, String idTypeLigne, String numCompte, String idEntite, String iddirection, String mois, int annee, String rmq, String nomTable) throws Exception, RemoteException;
  public String mapperDepenseLC(String idSortie, String idLC, String rem, String montant) throws Exception, RemoteException;
  public void validerMappageLCMRecette(String nomTable, String idMappage) throws Exception, RemoteException;
  public void validerMappageLCM(String nomTable, String idMappage) throws Exception, RemoteException;
  public UnionIntraTable validerMappageLCMavecOp(String nomTable, String idMere, String idOp) throws Exception, RemoteException;
  public void validerMappageLCMOpControle(String nomTable, String nomTableControl, String idMere) throws Exception, RemoteException;
  public void validerMappageLCMOrControle(String nomTable, String nomTableControl, String idMere) throws Exception, RemoteException;
  public void validerMappageLCMOp(String nomTable, String idMere) throws Exception, RemoteException;
  public void validerMappageLC(String nomTable, String[] idMappage) throws Exception, RemoteException;
  public void validerMappageAvecControle(String nomTable, String numObjet, String montObjTotal, Connection c) throws Exception, RemoteException;
  public void validerMappageAvecControle(String nomTable, String numObjet, String montObjTotal) throws Exception, RemoteException;
  public String mapperRecettesLC(String idEntree, String idLC, String rem, String montant) throws Exception, RemoteException;
  public String mapperFactureLC(String idFacture, String idLC, String rem, String montant) throws Exception, RemoteException;
  public String updateMontantUnionIntraLcOp(String nomTable, String nomTable2, String id1, String[] id2, String[] montant) throws Exception, RemoteException;
  public boolean deleteUnionIntraTableLcOp(String nomtable, String nomTable2, String id) throws Exception, RemoteException;
  public String mapperOpFactureFournisseurLCTableau(String idOp, String[] idLC, String rem, String[] montant) throws Exception, RemoteException;
  public String mapperFactureFournisseurLCTableau(String idFacture, String[] idLC, String rem, String[] montant) throws Exception, RemoteException;
  public String mapperFactureClientLCTableau(String idFacture, String[] idLC, String rem, String[] montant) throws Exception, RemoteException;
  public boolean deleteUnionIntraTable(String nomtable, String id) throws Exception, RemoteException;
  public String updateMontantUnionIntra(String nomTable, String id1, String[] id2, String[] montant) throws Exception, RemoteException;
  public String mapperFactureFournisseurLC(String idFacture, String idLC, String rem, String montant) throws Exception, RemoteException;
  public String copierLC(String mois, String annee, String mois0, String annee0, String nomTable) throws Exception, RemoteException;
  public String copierLCAvecDetail(String mois, String annee, String mois0, String annee0, String nomTable) throws Exception, RemoteException;
  public void updateLC(LigneCredit l) throws Exception, RemoteException;
  public String copierLC(String idLigneToCopy, String idEntite, String iddirection, String mois, String rmq, String annee) throws Exception, RemoteException;
  public String createDirection(String libelledir, String descdir, double idDirecteur, String abbrevDir) throws Exception, RemoteException;
  public String updateCreditLC(String idLigne, double newCredit, String motif) throws Exception, RemoteException;
  public Direction[] findDirection(String idDir, String libelledir, String descdir, String abbrevDir, String idDirecteur) throws Exception, RemoteException;
  public LigneCredit[] findLC(String idLigne, String designation, String idTypeLigne, String numCompte, String idEntite, String iddirection, String mois, String nomTable) throws Exception, RemoteException;
  public ResultatEtSomme findLCPage(String idLigne, String designation, String idTypeLigne, String numCompte, String idEntite, String iddirection, String mois, String nomTable, int numPage) throws Exception, RemoteException;
  public LigneCreditComplet[] findFCC(String idLigne, String designation, String mois1, String mois2, String typeLC, String numCompte, String descCompte, String libelledir, String abbrevdir, String entite, String idDirection, String colonne, String sens, String annee, String nomTable) throws Exception, RemoteException;
  public LigneCreditComplet[] findFCCParution(String idLigne, String designation, String mois1, String mois2, String typeLC, String numCompte, String descCompte, String libelledir, String abbrevdir, String entite, String idDirection, String colonne, String sens, String annee, String paruInf, String paruSup, String nomTable) throws Exception, RemoteException;
  public LigneCreditComplet[] findLCComplet(String idLigne, String designation, String mois, String typeLC, String numCompte, String descCompte, String libelledir, String abbrevdir, String entite, String idDirection, String colonne, String sens, String annee, String nomTable) throws Exception, RemoteException;
  public String updateDirection(String idToUpdate, String libelledir, String descdir, double idDirecteur, String abbrevDir) throws Exception, RemoteException;
  public String createEntiteFact(String nomT, String numFact, String designation, String date, String frns, String tva, String mTTC, String rmq, String datee, String idDevise, String nature) throws Exception, RemoteException;
  public String viser(String nomT, String daty, String remarque, String idObjet) throws Exception, RemoteException;
  public String viserDed(String daty, String remarque, String idObjet) throws Exception, RemoteException;
  public String viserOr(String daty, String remarque, String idObjet) throws Exception, RemoteException;
  public String viserOp(String daty, String remarque, String idObjet) throws Exception, RemoteException;
  public String ventilerDed(String idDed, String[] idLcDet, String[] montant, String[] remarque, String[] eta) throws Exception, RemoteException;
  public String ventilerOp(String idOp, String[] idLcDet, String[] montant, String[] remarque, String[] eta) throws Exception, RemoteException;
  public String ventilerMvtCaisseDebit(String idMvt, String[] idLcDet, String[] montant, String[] remarque, String[] eta, String nature) throws Exception, RemoteException;
  public String createDed(String desi, String daty, String mtht, String tax, String rem, String tiers, String idLigne) throws Exception, RemoteException;
  public String copierLcDetail(String idDepart, String idArrivee) throws Exception, RemoteException;
  public String createMvtCaisse(String daty, String datyValeur, String designation, String debit, String credit, String devise, String mode, String caisse, String remarque, String agence, String tier, String numP, String typeM) throws Exception, RemoteException;
  public String createMvtCaisseDirecte(String daty, String designation, String idLigne, String idFacture, String debit, String credit, String devise, String mode, String caisse, String remarque, String agence, String tier, String numP, String typeM) throws Exception, RemoteException;
  public String ventilerMvtCaisseLcDetailDepenseGroupe(String idDetLc, String idMvt, String rem, String montant) throws Exception, RemoteException;
  public String validerMvtCaisseLcDetailDepenseGroupe(String numMvtCaisse) throws Exception, RemoteException;
  public String createMvtCaisseDirecteRecette(String daty, String designation, String idLigne, String idFacture, String debit, String credit, String devise, String mode, String caisse, String remarque, String agence, String tier, String numP, String typeM) throws Exception, RemoteException;
  public String createMvtCaisseDirecteDepense(String daty, String designation, String idLigne, String idFacture, String debit, String credit, String devise, String mode, String caisse, String remarque, String agence, String tier, String numP, String typeM) throws Exception, RemoteException;
  public String retourVola(String idMvt, String idLcDet, String montant) throws Exception, RemoteException;
  public String annulerMvtDepense(String idMvt) throws Exception, RemoteException;
  public String createMvtCaisseDepenseRetour(String daty, String datyValeur, String designation, String debit, String devise, String mode, String caisse, String remarque, String agence, String tier, String numP, String typeM, String idOrdre, String idMvt) throws Exception, RemoteException;
  public String createMvtCaisseDepense(String daty, String datyValeur, String designation, String debit, String devise, String mode, String caisse, String remarque, String agence, String tier, String numP, String typeM, String idOrdre) throws Exception, RemoteException;
  public String validerAutoAnnulation(String id) throws Exception, RemoteException;
  public String createMvtCaisseRecette(String daty, String datyValeur, String designation, String credit, String devise, String mode, String caisse, String remarque, String agence, String tier, String numP, String typeM, String idOrdre) throws Exception, RemoteException;
  public MvtCaisse[] findMvtCaisse(String id, String daty1, String daty2, String datyVal1, String datyVal2, String designation, String devise, String mode, String caisse, String remarque, String agence, String tier, String numP, String typeM) throws Exception, RemoteException;
  public ResultatEtSomme findMvtCaisse(String id, String daty1, String daty2, String datyVal1, String datyVal2, String designation, String devise, String mode, String caisse, String remarque, String agence, String tier, String numP, String typeM, int numPage) throws Exception, RemoteException;
  public String creerOpDirecte(String daty, String designation, String idLigne, String idFacture, String debit, String tier, String remarque) throws Exception, RemoteException;
  public String creerOpDirecteSansVisa(String daty, String designation, String idLigne, String idFacture, String debit, String tier, String remarque) throws Exception, RemoteException;
  public String createOp(String idDed, String daty, String montant, String rem) throws Exception, RemoteException;
  public String createDetailMvtCaisse(String deb, String crd, String tiers, String rem, String paru, String idMere, String numP) throws Exception, RemoteException;
  public String createDetEntFact(String idM, String desi, String qte, String puHt, String rem) throws Exception, RemoteException;
  public FactureFournisseur[] findEntFact(String nomT, String id, String numFact, String designation, String frns, String montant1, String montant2, String rmq, String date1, String date2, String idDevise) throws Exception, RemoteException;
  public FactureFournisseur[] findFactureFournisseur(String nomTable, String num, String dateDebut, String dateFin, String fournisseur, String designation, String colonne, String ordre, String apresW) throws Exception, RemoteException;
  public DetailFact[] findDetailFact(String id, String idM, String desi, String mont1, String mont2, String rem) throws Exception, RemoteException;
  public Ded[] findDed(String id, String desi, String daty1, String daty2, String mont1, String mont2, String rem, String idLigne, String tiers) throws Exception, RemoteException;
  public ResultatEtSomme findDedPage(String id, String desi, String daty1, String daty2, String mont1, String mont2, String rem, String tiers, String idLigne, int numPage) throws Exception, RemoteException;
  public ResultatEtSomme findDedLcPage(String id, String desi, String daty1, String daty2, String mont1, String mont2, String rem, String tiers, String idLigne, String typeLc, String compte, String ent, String dir, String mois1, String mois2, int numPage) throws Exception, RemoteException;
  public DedLc[] findDedLc(String id, String desi, String daty1, String daty2, String mont1, String mont2, String rem, String tiers, String idLigne, String typeLc, String compte, String ent, String dir, String mois1, String mois2) throws Exception, RemoteException;
  public OrdonnerPayement[] findOp(String id, String idDed, String idLigne, String daty1, String daty2, String montant1, String mont2, String rem) throws Exception, RemoteException;
  public ResultatEtSomme findOpPage(String id, String idDed, String idLigne, String daty1, String daty2, String montant1, String mont2, String rem, int numPage) throws Exception, RemoteException;
  public ResultatEtSomme findOpPage(String nomTable, String id, String idDed, String idLigne, String daty1, String daty2, String montant1, String mont2, String rem, int numPage) throws Exception, RemoteException;
  public ResultatEtSomme findOpLcApayerPage(String nomTable, String id, String idDed, String idLigne, String daty1, String daty2, String montant1, String mont2, String annee1, String annee2, String typeLc, String compte, String ent, String dir, String mois1, String mois2, int numPage) throws Exception, RemoteException;
  public ResultatEtSomme findOrLcApayerPage(String nomTable, String id, String idDed, String idLigne, String daty1, String daty2, String montant1, String mont2, String annee1, String annee2, String typeLc, String compte, String ent, String dir, String mois1, String mois2, int numPage) throws Exception, RemoteException;
  public DetailMvtCaisse[] findDetMvtCaisse(String tiers, String rem, String idMere) throws Exception, RemoteException;
  public DetailMvtCaisse[] findDetMvtCaisseParu(String id, String tiers, String rem, String idMere, String paruInf, String paruSup) throws Exception, RemoteException;
  public ResultatEtSomme findDetMvtCaisseParu(String id, String tiers, String rem, String idMere, String paruInf, String paruSup, int numPage) throws Exception, RemoteException;
  public ResultatEtSomme findDetMvtCaisse(String tiers, String rem, String idMere, int numPage) throws Exception, RemoteException;
  public String mapperMereFille(String nomtableMappage, String nomFonctMap, String suffixeMap, String idMere, String idFille, String rem, String montant, String etat, Connection c) throws Exception, RemoteException;
  public String mapperMereFille(String nomtableMappage, String nomFonctMap, String suffixeMap, String idMere, String idFille, String rem, String montant, String etat) throws Exception, RemoteException;
  public String mapperMereFille(String nomtableMappage, String idMere, String idFille, String rem, String montant, String montantTot) throws Exception, RemoteException;
  public String insertMereFille(String nomtableMappage, String idMere, String idFille, String rem, String montant, String montantTot) throws Exception, RemoteException;
  public String deleteMereFille(String nomtableMappage, String idMappage) throws Exception, RemoteException;
  public UnionIntraTable[] findUnionIntraTable(String nomTable, String id, String id1, String id2, String rem, String mont1, String mont2, String eta, String apresW) throws Exception, RemoteException;
  public String creerMvtStock(String design, String type, String debit, String credit, String compte, String unite, String rmq) throws Exception, RemoteException;
  public String creerDossier(String idMvt, String typeDossier, String design, String num, String daty, String tiers, String qte, String mont, String rmq) throws Exception, RemoteException;
  public String creerDetailBobine(String numBob, String poids, String idMvt) throws Exception, RemoteException;
  public String creerParution(String journal, String numP, String datyP, String nbpage, String nbex, String poids, String printer, String idMvt, String rmq) throws Exception, RemoteException;
  public String creerLettrageMvt(String parent, String fille, String rmq) throws Exception, RemoteException;
  public String creerVerification(String mag, String reste, String unite, String controleur, String rmq) throws Exception, RemoteException;
  public String creerDetailVerifi(String numBob, String pourcentage, String verif, String rmq) throws Exception, RemoteException;
  public MvtStock[] findMvtStock(String idMvt, String datyInf, String datySup, String typeMvt, String compte) throws Exception, RemoteException;
  public Dossier[] findDossier(String id, String idMvt, String typeDossier, String datyInf, String datySup) throws Exception, RemoteException;
  public DetailBobinePoids[] findDetailBobine(String id, String numBobine, String idMvt) throws Exception, RemoteException;
  public Parution[] findParution(String id, String datyInf, String datySup, String journal, String datyParInf, String datyParSup, String printer, String idMvt) throws Exception, RemoteException;
  public LettrageMvt[] findLettrageMvt(String id, String parent, String fille) throws Exception, RemoteException;
  public Verification[] findVerification(String id, String datyInf, String datySup, String mag, String controleur) throws Exception, RemoteException;
  public DetailVerif[] findDetailVerif(String id, String numBob, String idVerif) throws Exception, RemoteException;
  public String updateDossier(String id, String idMvt, String typeDossier, String design, String num, String daty, String tiers, String qte, String mont, String rmq) throws Exception, RemoteException;
  public String enleverDetailBobine(String id) throws Exception, RemoteException;
  public String enleverDossier(String idDossier) throws Exception, RemoteException;
  public String faireMvtStock(String design, String type, String debitS, String creditS, String debitD, String creditD, String compteS, String compteD, String unite, String rmq) throws Exception, RemoteException;
  public double calculQte(String nbPage, String nbEx, String poids) throws Exception, RemoteException;
  public MvtCompte[] findMvtCompte(String idMvt, String datyInf, String datySup, String typeMvt, String compte, String val, String desce) throws Exception, RemoteException;
  public MvtBobine[] findMvtBobine(String idMvt, String datyInf, String datySup, String typeMvt, String compte, String numB) throws Exception, RemoteException;
  public String createDetailLc(String idLC, String compteDet, String cred, String montantEng, String montantVis, String montantFact) throws Exception, RemoteException;
  public String valideDetailLc(String idLC) throws Exception, RemoteException;
  public String updateDetailLc(String id, String idLC, String compteDet, String cred, String montantEng, String montantVis, String montantFact) throws Exception, RemoteException;
  public LcDetail[] findDetailLc(String id, String idLC, String compteDet, String etat) throws Exception, RemoteException;
  public String updateDed(String idDed, String desi, String daty, String mtht, String tax, String rem, String tiers) throws Exception, RemoteException;
  public String updateOp(String id, String daty, String mont) throws Exception, RemoteException;
  public String creerOR(String daty, String ligne, String mont, String eta) throws Exception, RemoteException;
  public OrdonnerPayement[] findOr(String id, String idLigne, String daty1, String daty2, String montant1, String mont2, String rem) throws Exception, RemoteException;
  public ResultatEtSomme findOrPage(String id, String ded, String idLigne, String daty1, String daty2, String montant1, String mont2, String rem, int numPage) throws Exception, RemoteException;
  public String createDetail(String nomTable, String idMere, String designation, String qte, String puHT, String rem) throws Exception, RemoteException;
  public String updateDetail(String nomTable, String id, String designation, String qte, String puHT, String rem) throws Exception, RemoteException;
  public Detail[] findDetail(String nomTable, String id, String idMere, String designation, String qte1, String qte2, String puHT1, String puHT2, String rem) throws Exception, RemoteException;
  public OpLc[] findOpLc(String id, String idDed, String idLigne, String daty1, String daty2, String montant1, String mont2, String rem, String typeLc, String compte, String ent, String dir, String mois1, String mois2) throws Exception, RemoteException;
  public ResultatEtSomme findOpLcPage(String id, String idDed, String idLigne, String daty1, String daty2, String montant1, String mont2, String rem, String typeLc, String compte, String ent, String dir, String mois1, String mois2, int numPage) throws Exception, RemoteException;
  public ResultatEtSomme findMvtCaisseLcPage(String id, String daty1, String daty2, String datyVal1, String datyVal2, String designation, String devise, String mode, String caisse, String remarque, String agence, String tier, String numP, String typeM, String idLigne, String typeLc, String compte, String ent, String dir, String mois1, String mois2, int numPage) throws Exception, RemoteException;
  public MvtCaisseLc[] findMvtCaisseLc(String id, String daty1, String daty2, String datyVal1, String datyVal2, String designation, String devise, String mode, String caisse, String remarque, String agence, String tier, String numP, String typeM, String idLigne, String typeLc, String compte, String ent, String dir, String mois1, String mois2) throws Exception, RemoteException;
  public Cheque[] findCheque(String id, String mvt, String datyS1, String datyS2, String datyV1, String datyV2, String ord, String rem, String numC, String ca) throws Exception, RemoteException;
  public Cheque createCheque(String mvt, String datyS, String datyV, String ord, String rem, String numC, String ca, String mont) throws Exception, RemoteException;
  public String degagerDed(String idDed) throws Exception, RemoteException;
  public String degagerOp(String idOp) throws Exception, RemoteException;
  public String degagerMvtCaisse(String idMvt) throws Exception, RemoteException;
  public String viserFactureF(String refFact, String rem) throws Exception, RemoteException;
  public FactureFournisseur createOrSimple(String daty, String montant, String idTva, String idFrns, String idDevise, String resp, String rem) throws Exception, RemoteException;
  public OrdonnerPayement annulerOp(String nomTable, String nomTableLiaison, String id) throws Exception, RemoteException;
  public FactureFournisseur createOpSimple(String daty, String montant, String idTva, String idFrns, String idDevise, String rem) throws Exception, RemoteException;
  public SaisieVirement[] findVirementNormale(String nomtable, String id, String dev, String caisse1, String caisse2, String mode, String daty1, String daty2, String apreW) throws RemoteException;
  public String updateLC(String idLigne, String designation, String creditIni, String creditMod, String typeLigne, String numCompte, String entite, String dir, String mois, String annee, String nomTable) throws Exception, RemoteException;
  public String copierLCRecette(String mois, String annee, String mois0, String annee0, String nomTable) throws Exception, RemoteException;
  public String viserFactureC(String idFact, String remarque) throws Exception, RemoteException;
  public String mapperFactureClientLC(String idFacture, String idLC, String rem, String montant) throws Exception, RemoteException;
  public String mapperOrFactureClientLCTableau(String idOp, String[] idLC, String rem, String[] montant) throws Exception, RemoteException;
  public ResultatEtSomme findFactureFournisseurPageLc(String nomtable, String id, String fourn, String designation, String numFact, String idLigne, String daty1, String daty2, String desiLc, String mois1Lc, String mois2Lc, String anneeLc, String dirLc, String entiteLc, String typeLc, String compteLc, int numPage, String colonne, String ordre) throws Exception, RemoteException;
  public ResultatEtSomme findOpPageLc(String nomtable, String id, String idDed, String idLigne, String daty1, String daty2, String etat, String desiLc, String mois1Lc, String mois2Lc, String anneeLc, String dirLc, String entiteLc, String typeLc, String compteLc, int numPage) throws Exception, RemoteException;
  public String creerTache(Tache t) throws Exception, RemoteException;
  public String transfererTache(String t, String userFinal) throws Exception, RemoteException;
  public String modifierTache(Tache t) throws Exception, RemoteException;
  public void effectuerTache(EffTache ef) throws Exception, RemoteException;
  public String commenterTache(TypeObjet tc) throws Exception, RemoteException;
  public TacheVue[] findTache(TacheVue crt, String daty1, String daty2, String apresWher) throws Exception, RemoteException;
  public ResultatEtSomme findTachePage(Tache crt, String daty1, String daty2, String apresWher, int numPage) throws Exception, RemoteException;
  public MapUtilisateur[] findUserSubordonnee() throws Exception, RemoteException;
  public Publicite updatePub(Publicite p) throws Exception, RemoteException;
  public Publicite[] createPub(String parution1, String parution2, String idClient, String designation, String dimension, String couleur, String page, String journal, String bc, String rem, String cat, String resp, String numP, String formu, String remis) throws Exception, RemoteException;
  public int remiserPub(String[] idPub, String[] listePage) throws Exception, RemoteException;
  public int corrigerPub(String[] idPub, String[] corr) throws Exception, RemoteException;
  public int mettrePage(String[] idPub, String[] listePage, String[] listePageAncien) throws Exception, RemoteException;
  public void corrigerPub(String idP) throws Exception, RemoteException;
  public Publicite[] findPub(Publicite crt, String[] colInt, String[] valInt, String aW) throws Exception, RemoteException;
  public ResultatEtSomme getDataPage(ClassMAPTable e, String[] colInt, String[] valInt, int numPage, String apresWhere, String[] nomColSomme, Connection c) throws Exception, RemoteException;
  public ResultatEtSomme getDataPage(ClassMAPTable e, String[] colInt, String[] valInt, int numPage, String apresWhere, String[] nomColSomme, Connection c, int npp) throws Exception, RemoteException;
  public ResultatEtSomme getDataPageGroupe(ClassMAPTable e, String[] groupe, String[] sommeGroupe, String[] colInt, String[] valInt, int numPage, String apresWhere, String[] nomColSomme, String ordre, Connection c) throws Exception, RemoteException;
  public ResultatEtSomme getDataPageGroupe(ClassMAPTable e, String[] groupe, String[] sommeGroupe, String[] colInt, String[] valInt, int numPage, String apresWhere, String[] nomColSomme, String ordre, Connection c, int npp) throws Exception, RemoteException;
  public Object[] getData(ClassMAPTable e, String[] colInt, String[] valInt, Connection c, String apresWhere) throws Exception, RemoteException;
  public Remise[] createRemise(String[] idPub, String remise) throws Exception, RemoteException;
  public int getint() throws RemoteException;
  public Object createObject(ClassMAPTable o) throws Exception, RemoteException;
  public Object updateObject(ClassMAPTable o) throws Exception, RemoteException;
  public void deleteObject(ClassMAPTable o) throws Exception, RemoteException;
  public Parution creerParution(String par1, String dateP, String journ, String nbpage, String remarque) throws Exception, RemoteException;
  public void facturerPub(String idFacture, String idPub) throws Exception, RemoteException;
  public void validerFacturerPub(String idFacture) throws Exception, RemoteException;
  public void validerMappage(String idFacture, String nomTable) throws Exception, RemoteException;
  public boolean isSuperUser() throws RemoteException;
  public void setIdDirection(String idDirection) throws RemoteException;
  public String getIdDirection() throws RemoteException;
  //public Parution creerParution(String par1, String par2, String journ) throws Exception, RemoteException;
}
