CREATE SEQUENCE SEQ_PUB_TYPE;
CREATE SEQUENCE SEQ_PUB_TARIF;
CREATE SEQUENCE SEQ_PUB_PLAGE_HORAIRE;
CREATE SEQUENCE SEQ_PUB_CLIENT;
CREATE SEQUENCE SEQ_PUB_CLIENT_FILLE;

CREATE TABLE PUB_TYPE(	
	ID VARCHAR2(50) PRIMARY KEY,
	DESIGNATION VARCHAR2(100),
	TYPE VARCHAR2(50),
	DUREE NUMBER,
	DUREES VARCHAR2(100)
);

CREATE TABLE PUB_PLAGE_HORAIRE(	
	ID VARCHAR2(50) PRIMARY KEY,
	DESIGNATION VARCHAR2(100),
	NUMERO VARCHAR2(100),
	HEURE_DEBUT VARCHAR2(50),
	HEURE_FIN VARCHAR2(50)
);

CREATE TABLE PUB_TARIF(	
	ID VARCHAR2(50) PRIMARY KEY,
	IDTYPE VARCHAR2(50),
	DUREE NUMBER,
	DUREES VARCHAR2(100),	
	ID_PLAGE_HORAIRE VARCHAR2(50)
);

CREATE TABLE PUB_CLIENT(
	ID VARCHAR2(50) PRIMARY KEY,
	CLIENT VARCHAR2(50),
	NOM_COMPAGNE VARCHAR2(100)
);

CREATE TABLE PUB_CLIENT_FILLE(
	ID VARCHAR2(50) PRIMARY KEY,
	MERE VARCHAR2(50),
	NOM_PUB VARCHAR2(100),
	REF VARCHAR2(100),
	DUREE NUMBER,
	IDTYPE VARCHAR2(50),
	IDPLAGE VARCHAR2(50),
	DATE_DEBUT_DIFF DATE,
	DATE_FIN_DIFF DATE,
	QTE NUMBER,
	REMARQUES VARCHAR2(100)
);

ALTER TABLE PUB_TARIF ADD FOREIGN KEY(IDTYPE) 					REFERENCES PUB_TYPE(ID);
ALTER TABLE PUB_TARIF ADD FOREIGN KEY(ID_PLAGE_HORAIRE)			REFERENCES PUB_PLAGE_HORAIRE(ID);
ALTER TABLE PUB_CLIENT_FILLE ADD FOREIGN KEY(IDTYPE) 			REFERENCES PUB_TYPE(ID);
ALTER TABLE PUB_CLIENT_FILLE ADD FOREIGN KEY(IDPLAGE) 			REFERENCES PUB_PLAGE_HORAIRE(ID);
ALTER TABLE PUB_CLIENT ADD FOREIGN KEY(CLIENT)					REFERENCES CLIENT(IDCLIENT);
ALTER TABLE PUB_CLIENT_FILLE ADD FOREIGN KEY(MERE) 				REFERENCES PUB_CLIENT(ID);

CREATE or REPLACE
FUNCTION GETSEQPUBTYPE
   RETURN NUMBER
IS
   retour   NUMBER;
BEGIN
   SELECT SEQ_PUB_TYPE.NEXTVAL INTO retour FROM DUAL;

   RETURN retour;
END;
/


CREATE or REPLACE
FUNCTION GETSEQPUBTARIF
   RETURN NUMBER
IS
   retour   NUMBER;
BEGIN
   SELECT SEQ_PUB_TARIF.NEXTVAL INTO retour FROM DUAL;

   RETURN retour;
END;
/

CREATE or REPLACE
FUNCTION GETSEQPUBPLAGEHORAIRE
   RETURN NUMBER
IS
   retour   NUMBER;
BEGIN
   SELECT SEQ_PUB_PLAGE_HORAIRE.NEXTVAL INTO retour FROM DUAL;

   RETURN retour;
END;
/

CREATE or REPLACE
FUNCTION GETSEQPUBCLIENT
   RETURN NUMBER
IS
   retour   NUMBER;
BEGIN
   SELECT SEQ_PUB_CLIENT.NEXTVAL INTO retour FROM DUAL;

   RETURN retour;
END;
/

CREATE or REPLACE
FUNCTION GETSEQPUBCLIENTFILLE
   RETURN NUMBER
IS
   retour   NUMBER;
BEGIN
   SELECT SEQ_PUB_CLIENT_FILLE.NEXTVAL INTO retour FROM DUAL;

   RETURN retour;
END;
/

create or replace view pub_client_libelle as 
select m.id,c.nom as client, m.nom_compagne,f.nom_pub,f.ref,f.duree,t.designation as idtype ,p.numero as idplage,
f.date_debut_diff,f.date_fin_diff,f.qte,f.remarques
from pub_client m 
join client c on m.client=c.idclient 
join pub_client_fille f 
join pub_type t on f.idtype=t.id
join pub_plage_horaire p on f.idplage=p.id
on m.id=f.mere;
