CREATE VIEW MVTCAISSESOMMEDEBIT AS
select idordre as ID, sum(debit) as SOMMEMONTANT from mvtcaisse group by idordre;

CREATE OR REPLACE VIEW ORDONNERPAYEMENTRESTE as
select
orp.ID,
orp.DATY,
orp.MONTANT,
mvtc.SOMMEMONTANT as PAYE,
(orp.MONTANT - mvtc.SOMMEMONTANT) as RESTE
FROM 
ORDONNERPAYEMENT orp,
MVTCAISSESOMMEDEBIT mvtc,
VISAORDREPAYEMENT v
WHERE orp.ID = mvtc.ID(+)
AND (orp.MONTANT - mvtc.SOMMEMONTANT) > 100
AND orp.ID = v.IDOBJET

